# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('upwd', models.CharField(max_length=40)),
                ('uaddress', models.CharField(max_length=100)),
                ('ushoujian', models.CharField(max_length=20)),
                ('uemail', models.CharField(max_length=20)),
                ('ucode', models.IntegerField(max_length=6)),
                ('uphone', models.IntegerField(max_length=11)),
            ],
        ),
    ]
